plugins {
    id "com.android.application"
}

android {
    namespace "com.introskip.player"
    compileSdk 35

    defaultConfig {
        applicationId "com.introskip.player"
        minSdk 26
        targetSdk 35
        versionCode 29
        versionName "2.18"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
